[package]
name = "ferinth"
# The major version specifies which version of the Modrinth API this supports
version = "2.5.1"
edition = "2021"
authors = ["Ilesh Thiada (theRookieCoder) <ileshkt@gmail.com>", "4JX"]
description = "A simple Rust wrapper for the official Modrinth API "
repository = "https://github.com/theRookieCoder/ferinth"
license = "MIT"
publish = ["crates-io"]
keywords = ["modrinth", "minecraft", "modding"]
categories = ["api-bindings"]

[dependencies]
reqwest = { version = "~0.11.11", default-features = false, features = [
    "json",
    "rustls-tls",
] }
serde = { version = "~1.0.138", features = ["derive"] }
chrono = { version = "~0.4.19", features = ["serde"] }
url = { version = "~2.2.2", features = ["serde"] }
lazy_static = "~1.4.0"
serde_json = "~1.0.82"
lazy-regex = "~2.3.0"
thiserror = "~1.0.31"

[dev-dependencies]
tokio = { version = "~1.19.2", features = ["rt-multi-thread", "macros"] }
