[package]
name = "ferinth"
# The major version specifies which version of the Modrinth API this supports
version = "2.7.0"
edition = "2021"
authors = ["Ilesh Thiada (theRookieCoder) <ileshkt@gmail.com>", "4JX"]
description = "A simple Rust wrapper for the official Modrinth API"
repository = "https://github.com/gorilla-devs/ferinth"
license = "MIT"
publish = ["crates-io"]
keywords = ["modrinth", "minecraft", "modding"]
categories = ["api-bindings"]

[dependencies]
reqwest = { version = "~0.11.12", default-features = false, features = [
    "json",
    "rustls-tls",
] }
serde = { version = "~1.0.145", features = ["derive"] }
chrono = { version = "~0.4.22", features = ["serde"] }
url = { version = "~2.3.1", features = ["serde"] }
lazy_static = "~1.4.0"
serde_json = "~1.0.85"
lazy-regex = "~2.3.0"
thiserror = "~1.0.37"

[dev-dependencies]
tokio = { version = "~1.21.2", features = ["rt-multi-thread", "macros"] }
